# 数据源相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
    #  数据库连接的URL，数据库名称为zz_home，需要现在数据库中创建一个空的数据库：create database zz_home;
    url: jdbc:mysql://localhost:3306/zz_home?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource  # 采用Apache Druid数据库连接池的时候采用此数据源
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 当修改实体时，对应可以修改更新表结构
    show-sql: true  # 是否展示SQL
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: mysql
    open-in-view: true
  data:
    rest:
      default-page-size: 10
